app:
  name: "Weyoto GitGPT"
  uses_create_app: true
  blueprint_root: "modules"
  extensions:
    - Flask-SQLAlchemy

deployment:
  provider: "Render (Dev/Staging)"
  local_proxy: "Cloudflare Tunnel"
  env_file: "N/A"
  uses_system_env_vars: true
  schema_path: "gpt/schema/"

auth:
  api_key_header: "x-api-key"
  user_identifier: "email"
  shared_across_sources: true

billing:
  plans:
    free: 30/day
    pro: unlimited

data_sources:
  github:
    blueprint: "github_bp"
    auth_type: "PAT"
    permissions:
      contents: read
      metadata: read
      statuses: read
    env_keys: []

schema:
  directory: "gpt/schema/"
  changelog: "gpt-schema-changelog.md"

env_required:
  - WEYOTO_GITGPT_DATABASE_URL
  - WEYOTO_API_KEY_SECRET
  - WEYOTO_ALLOWED_ORIGINS
  - RESEND_API_KEY
  - EMAIL_SENDER

