"""Add GitHub OAuth token fields

Revision ID: 862f435cc8e8
Revises: 92eee3d38377
Create Date: 2025-05-10 17:06:37.560368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862f435cc8e8'
down_revision = '92eee3d38377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_token', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('github_token')

    # ### end Alembic commands ###
