"""Add last_code_sent_at to User

Revision ID: 92eee3d38377
Revises: f23c83ae6b00
Create Date: 2025-05-04 17:37:43.799420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92eee3d38377'
down_revision = 'f23c83ae6b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_code_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_code_sent_at')

    # ### end Alembic commands ###
