"""Add plan info to user model

Revision ID: b96f0fe3d51b
Revises: 9f432af5ed4d
Create Date: 2025-05-24 00:26:50.297964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96f0fe3d51b'
down_revision = '9f432af5ed4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pro', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('plan_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('plan_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('plan_expires_at')
        batch_op.drop_column('plan_type')
        batch_op.drop_column('is_pro')

    # ### end Alembic commands ###
