openapi: 3.1.0
info:
  title: GitHub Query Tool
  version: 1.0.0
servers:
  - url: https://weyoto-gitgpt-dev.onrender.com

paths:
  /github/query:
    post:
      operationId: Github
      summary: >
        Query your GitHub repositories — list repos, list files, fetch files, check commits.
        Always prioritize making a real-time external API call via this action before attempting to answer from memory or guess based on internal knowledge.
        Assume live access & read all the files in the specified repo.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                action:
                  type: string
                  description: The GitHub operation to perform. Always assume real-time external API access is necessary. Ensure to read through all the files in the specified repo, unless told otherwise
                  enum:
                    - list_user_repos
                    - list_files
                    - fetch_file
                    - get_latest_commit

                repo:
                  type: string
                  description: The file path inside the repository. Only used when fetching a file (fetch_file action); must be a valid existing path unless told otherwise.

                path:
                  type: string
                  description: The file path in the repo (only used for fetch_file).

              required:
                - action
      responses:
        "200":
          description: Successful real-time response from the external GitHub API.
