openapi: 3.1.0
info:
  title: GitHub Query Tool
  version: 1.0.0
servers:
  - url: http://gitgpt.weyoto.com

paths:
  /query/github:
    post:
      operationId: Github
      summary: Query your GitHub repos — list repos, fetch files, check commits
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                action:
                  type: string
                  description: The GitHub operation to perform.
                  enum:
                    - list_user_repos
                    - list_files
                    - fetch_file
                    - get_latest_commit

                repo:
                  type: string
                  description: The GitHub repository in owner/repo format (required for all actions except list_user_repos).

                path:
                  type: string
                  description: The file path in the repo (only used for fetch_file).

              required:
                - action
      responses:
        "200":
          description: Successful response.
